import { Component, OnInit} from '@angular/core';
import { FormBuilder } from '@angular/forms';
import { Router } from '@angular/router';
import { EmployeeService } from 'src/app/service/employee.service';
import { Observable, timer } from 'rxjs';
import { switchMap } from 'rxjs/operators';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  images = ['assets/images/email.png', 'assets/images/PDF.jpg', 'assets/images/userLogin.png'];
  imagesBack=['assets/images/homeBackground.png']
  currentImageIndex = 0;
  public userName:string;
  homeBackground:'assets/images/homeBackground.png';
  // An observable that emits every 5 seconds
  timer$: Observable<number> = timer(0, 3000);
  getImageStyle(){
    return {
        //this.image is the image URL that has been generated by your changeImage() function
        backgroundImage:`url(${this.images[this.currentImageIndex]})`,
        //It's important to redefine the background position because it will not be used if no `backgroundImage` is provided 
        backgroundPosition:'center center',
        backgroundRepeat:'no-repeat',
        backgroundSize:'cover'
      }
  }
  getBackgroudStyle(){
    return {
      //this.image is the image URL that has been generated by your changeImage() function
      backgroundImage:`url(${this.imagesBack[0]})`,
      backgroundPosition:'center center',
      backgroundRepeat:'no-repeat',
    
    }
  }
  ngOnInit() {
   console.log("in home welcome",this.employeeService.GetUser())
    this.userName = this.employeeService.GetUser().employeeName;
    this.timer$.subscribe(() => {
      this.currentImageIndex = (this.currentImageIndex + 1) % this.images.length;
    });
  }

constructor(private router : Router, private fb:FormBuilder, public employeeService:EmployeeService
  ,private toastr:ToastrService){}

}


